# Generated by Django 2.0 on 2018-05-09 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTO_vocabulary',
            fields=[
                ('idBTO_vocab', models.AutoField(primary_key=True, serialize=False)),
                ('words', models.CharField(max_length=200, unique=True)),
                ('BTO_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Data_source',
            fields=[
                ('idSource', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gene_Protein',
            fields=[
                ('idGene_Protein', models.AutoField(primary_key=True, serialize=False)),
                ('EntrezID', models.IntegerField(unique=True)),
                ('UniprotACC', models.CharField(default='EMPTY', max_length=50)),
                ('GeneName', models.CharField(default='EMPTY', max_length=50)),
                ('GeneSymbol', models.CharField(default='EMPTY', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PubAnnotation',
            fields=[
                ('idPubAnnotation', models.AutoField(primary_key=True, serialize=False)),
                ('annotaion', models.CharField(max_length=5000)),
                ('pmid', models.IntegerField(default=-1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PubFulltext',
            fields=[
                ('idPubFulltext', models.AutoField(primary_key=True, serialize=False)),
                ('fulltext', models.CharField(max_length=1000)),
                ('pmid', models.IntegerField(default=-1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PubMed_entry',
            fields=[
                ('idPubMed_entry', models.AutoField(primary_key=True, serialize=False)),
                ('pmid', models.IntegerField(unique=True)),
                ('authors', models.CharField(default='No details', max_length=200)),
                ('journal', models.CharField(default='No details', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PubTokens',
            fields=[
                ('idPubTokens', models.AutoField(primary_key=True, serialize=False)),
                ('tokens', models.CharField(max_length=1000)),
                ('pmid', models.IntegerField(default=-1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Relation_Pub_Anno',
            fields=[
                ('idRelation_Pub_Anno', models.AutoField(primary_key=True, serialize=False)),
                ('pmid', models.IntegerField(default=-1, unique=True)),
                ('id_pub_anno', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='ts_scl_db.PubAnnotation')),
                ('id_pub_fulltext', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='ts_scl_db.PubFulltext')),
                ('id_pub_token', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='ts_scl_db.PubTokens')),
            ],
        ),
        migrations.CreateModel(
            name='SCL_vocabulary',
            fields=[
                ('idSCL_vocab', models.AutoField(primary_key=True, serialize=False)),
                ('words', models.CharField(max_length=200, unique=True)),
                ('GO_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SCLocalization',
            fields=[
                ('idSCL', models.AutoField(primary_key=True, serialize=False)),
                ('GO_id', models.CharField(max_length=50, unique=True)),
                ('SCL_term', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TempHighLightedText',
            fields=[
                ('idPubFulltext', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('fulltext', models.CharField(max_length=1000)),
                ('pmid', models.IntegerField(default=-1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tissue',
            fields=[
                ('idTissue', models.AutoField(primary_key=True, serialize=False)),
                ('BTO_id', models.CharField(max_length=50, unique=True)),
                ('BTO_term', models.CharField(default='EMPTY', max_length=50)),
                ('BTO_link', models.CharField(default='EMPTY', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tissue_triple_relation',
            fields=[
                ('idTissue_triple_relation', models.AutoField(primary_key=True, serialize=False)),
                ('Zscore', models.FloatField(default=-1)),
                ('reliability', models.CharField(default='', max_length=10)),
                ('review', models.CharField(default='No', max_length=10)),
                ('id_BTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ts_scl_db.Tissue')),
                ('id_Entrez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ts_scl_db.Gene_Protein')),
                ('id_GO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ts_scl_db.SCLocalization')),
                ('source', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='ts_scl_db.Data_source')),
            ],
        ),
        migrations.CreateModel(
            name='Tissue_triple_relation_pmid',
            fields=[
                ('idTissue_triple_relation_pmid', models.AutoField(primary_key=True, serialize=False)),
                ('Tissue_triple_relation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ts_scl_db.Tissue_triple_relation')),
                ('id_pmid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ts_scl_db.PubMed_entry')),
            ],
        ),
        migrations.AddField(
            model_name='pubmed_entry',
            name='id_Pub_Anno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ts_scl_db.Relation_Pub_Anno'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ts_scl_db.Question'),
        ),
    ]
