# Generated by Django 2.0 on 2018-05-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_scl_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sclocalization',
            name='SCL_term',
            field=models.CharField(max_length=100),
        ),
    ]
