# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_scl_db', '0004_pageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubmed_entry',
            name='journal',
            field=models.CharField(default='No details', max_length=200),
        ),
    ]
